version: '3.8'

services:
  backend:
    build: ./backend
    container_name: taskmaster-backend
    ports:
      - "5000:5000"
    volumes:
      # Esto permite editar código en tu PC y que se actualice en el contenedor
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: taskmaster-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobrescribir node_modules del contenedor
    depends_on:
      - backend # Espera a que el backend inicie
